### ISSUE TITLE
Shared volume doesn't exist when docker runs ssh command

### ISSUE THREAD

**Issue by acidreign** [cagataygurturk/docker-ssh-tunnel#1]
The container is missing the shared volume `/root/.ssh` when it runs the ssh command. 

This results in an error message: `Bad owner or permissions on /root/.ssh/config`

Did you ever get this to work? I'm looking into a similar setup.

**Comment by cagataygurturk** [comment]
Are you at linux? I've heard some people had the same issue. You can put ssh config to another directory and mount it as volume or alternatively you can build another docker image on top of it and copy your config and private key into new docker image maybe.

**Comment by JGladykowski-modus** [comment]
I encountered same issue using Windows. Solution in docker-compose.yml:

```
    volumes:
      - $HOME/.ssh:/root/tmp:ro
    command: ash -c "mkdir /root/.ssh && cp /root/tmp/* /root/.ssh/ && chmod 600 /root/.ssh/* && ssh -vv -o StrictHostKeyChecking=no -Nn ${TUNNEL_HOST} -L *:${LOCAL_PORT}:${REMOTE_HOST}:${REMOTE_PORT}"
```

**Comment by cagataygurturk** [comment]
@JGladykowski-modus do you think it will make sense to apply this command to Dockerfile, so it becomes a generic solutions for all?

**Comment by JGladykowski-modus** [comment]
@cagataygurturk  I think yes :) We tried different workarounds, but only this one worked. I wanted to make pull request, but Github said no :)

**Comment by cagataygurturk** [comment]
I integrated the solution into Dockerfile. Now you don't have to build the image yourself, you can basically use as follows:

```
    version: '2'
    services:
      mysql:
        image: cagataygurturk/docker-ssh-tunnel:0.0.1
        volumes:
          - $HOME/.ssh:/root/ssh:ro
        environment:
          TUNNEL_HOST: mysql-tunnel
          REMOTE_HOST: tunneled-sql.corporate.internal.tld
          LOCAL_PORT: 3306
          REMOTE_PORT: 3306
```
